name: Package and Release Sources

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version tag'
        required: true

  push:
    tags:
      - 'v*.*.*'

jobs:
  package:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: zip_sources
      id: zip_sources
      env:
        VERSION: ${{ github.event.inputs.version || github.ref_name }}
      run: |
        script_output=$(python scripts/pack_sources.py)
        zip_file=$(echo "$script_output" | sed -n '1p')
        version=$(echo "$script_output" | sed -n '2p')
        echo "zip_file=$zip_file" >> $GITHUB_ENV
        echo "version=$version" >> $GITHUB_ENV

    - name: Create GitHub Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ env.version }}
        release_name: Release ${{ env.version }}
        draft: false
        prerelease: false

    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ${{ env.zip_file }}
        asset_name: sources.zip
        asset_content_type: application/zip